---
version: "3.9"
services:
  coder:
    image: ghcr.io/coder/coder:v2.15.0@sha256:aa0cc5667c74bce496c0b057eae3a2c042c17e7cd81069e2fef626ebe4def4cc
    ports:
    - "${AVAILABLE_PORT:-8080}:8080"
    environment:
      CODER_PG_CONNECTION_URL: "postgresql://coder:coder@database/coder?sslmode=disable"
      CODER_HTTP_ADDRESS: "0.0.0.0:8080"
      CODER_TELEMETRY_ENABLE: false
      CODER_ACCESS_URL: "http://127.0.0.1:${AVAILABLE_PORT:-8080}"
      CODER_ENABLE_TERRAFORM_DEBUG_MODE: true
    # add write permissions on the mounted docker socket to enable coder user to start containers
    group_add:
    - "${DOCKER_GROUP:-999}" # docker group on host
    volumes:
    # needed for coder to be able to launch workspaces w/ docker provisioner
    - /var/run/docker.sock:/var/run/docker.sock
    # mount /var/lib/docker from host so that image that was built by CI but not published yet is available to workspace
    - /var/lib/docker:/var/lib/docker
    depends_on:
      database:
        condition: service_healthy
  database:
    image: "postgres:16.4@sha256:c62fdb7fd6f519ef425c54760894c74e8d0cb04fbf4f7d3d79aafd86bae24edd"
    environment:
      POSTGRES_USER: coder
      POSTGRES_PASSWORD: coder
      POSTGRES_DB: coder
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U coder -d coder",
        ]
      interval: 5s
      timeout: 5s
      retries: 5
