---
version: "3.9"
services:
  coder:
    image: ghcr.io/coder/coder:v2.12.1@sha256:74a84fe33fb99540f8fc9b038f8a72cff66d0561ce9866de5ea2ab9e8bca3a2d
    ports:
    - "${AVAILABLE_PORT:-8080}:8080"
    environment:
      CODER_PG_CONNECTION_URL: "postgresql://coder:coder@database/coder?sslmode=disable"
      CODER_HTTP_ADDRESS: "0.0.0.0:8080"
      CODER_TELEMETRY_ENABLE: false
      CODER_ACCESS_URL: "http://127.0.0.1:${AVAILABLE_PORT:-8080}"
    # add write permissions on the mounted docker socket to enable coder user to start containers
    group_add:
    - "${DOCKER_GROUP:-999}" # docker group on host
    volumes:
    # needed for coder to be able to launch workspaces w/ docker provisioner
    - /var/run/docker.sock:/var/run/docker.sock
    # mount /var/lib/docker from host so that image that was built by CI but not published yet is available to workspace
    - /var/lib/docker:/var/lib/docker
    depends_on:
      database:
        condition: service_healthy
  database:
    image: "postgres:14.12@sha256:da8b991e3909fc95a272fcbeb1e0d79ce1a7028fe1549b1ba0ed0a6a45e126cb"
    environment:
      POSTGRES_USER: coder
      POSTGRES_PASSWORD: coder
      POSTGRES_DB: coder
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U coder -d coder",
        ]
      interval: 5s
      timeout: 5s
      retries: 5
