[supervisord]
logfile=%(ENV_HOME)s/.local/state/supervisor/supervisord.log
pidfile=%(ENV_HOME)s/.local/state/supervisor/supervisord.pid
childlogdir=%(ENV_HOME)s/.local/state/supervisor
nodaemon=false

[unix_http_server]
file=%(ENV_HOME)s/.local/state/supervisor/supervisor.sock

[supervisorctl]
serverurl=unix://%(ENV_HOME)s/.local/state/supervisor/supervisor.sock

[rpcinterface:supervisor]
supervisor.rpcinterface_factory=supervisor.rpcinterface:make_main_rpcinterface

[program:service]
process_name=service-%(process_num)s
numprocs=%(ENV_SUPERVISOR_SERVICE_COUNT)s
numprocs_start=0
command=/bin/bash /service-command.sh %(process_num)s
directory=%(ENV_HOME)s
autostart=true
autorestart=true
startsecs=1
stopasgroup=true
killasgroup=true
redirect_stderr=true
stdout_logfile=%(ENV_HOME)s/.local/state/supervisor/service-%(process_num)s.log
stdout_logfile_maxbytes=10MB
stdout_logfile_backups=2
