---
collections:
- name: ansible.posix
  version: 1.5.4
- name: ansible.utils
  version: 2.12.0
- name: community.docker
  version: 3.10.4
- name: community.general
  version: 8.6.2
- name: kubernetes.core
  version: 2.4.2
