---
collections:
- name: ansible.posix
  version: 1.5.4
- name: ansible.utils
  version: 5.1.0
- name: community.docker
  version: 3.12.1
- name: community.general
  version: 9.3.0
- name: kubernetes.core
  version: 5.0.0
