---
collections:
- name: ansible.posix
  version: 2.0.0
- name: ansible.utils
  version: 5.1.2
- name: community.docker
  version: 4.1.0
- name: community.general
  version: 10.1.0
- name: kubernetes.core
  version: 5.0.0
