---
collections:
- name: ansible.posix
  version: 1.5.4
- name: ansible.utils
  version: 5.0.0
- name: community.docker
  version: 3.11.0
- name: community.general
  version: 9.2.0
- name: kubernetes.core
  version: 5.0.0
