---
collections:
- name: ansible.posix
  version: 1.6.0
- name: ansible.utils
  version: 5.1.1
- name: community.docker
  version: 3.12.1
- name: community.general
  version: 9.4.0
- name: kubernetes.core
  version: 5.0.0
