---
# yamllint disable rule:line-length
name: release

on:
  pull_request:
    paths:
    - '.github/workflows/release.yaml'
    - 'release-please-config.json'
  push:
    branches:
    - main
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

permissions: {}

jobs:
  release:
    uses: ppat/github-workflows/.github/workflows/release-please.yaml@54ce2e4ac00927d6164d032b321f0142aab01c69 # v6.1.0
    with:
      dry_run: ${{ github.event_name == 'pull_request' }}
    secrets:
      app_id: ${{ secrets.HOMELAB_BOT_APP_ID }}
      app_private_key: ${{ secrets.HOMELAB_BOT_APP_PRIVATE_KEY }}
