---
# yamllint disable rule:line-length
name: test image

on:
  pull_request:
    paths:
    - .github/workflows/test-image.yaml
    - images/homelab-workspace/**

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  build:
    permissions:
      contents: read
      packages: write
    uses: ppat/github-workflows/.github/workflows/build-docker-image.yaml@54ce2e4ac00927d6164d032b321f0142aab01c69 # v6.1.0
    with:
      image_context_path: images/homelab-workspace
      label_title: "Homelab Workspace"
      label_description: "Homelab workspace image"
      platforms: linux/amd64,linux/arm64
      private_registry_repository: ${{ vars.CONTAINER_REGISTRY_PATH }}/coder-workspace
      private_registry_build_cache: ${{ vars.CONTAINER_REGISTRY_CACHE_PATH }}/coder-workspace
      git_ref: ${{ github.head_ref }}
      timeout_minutes: 180
    secrets:
      private_registry_username: ${{ secrets.CONTAINER_REGISTRY_USERNAME }}
      private_registry_token: ${{ secrets.CONTAINER_REGISTRY_PASSWORD }}
      private_registry: ${{ secrets.CONTAINER_REGISTRY }}
      tailscale_oauth_client_id: ${{ secrets.TAILSCALE_OAUTH_CLIENT_ID }}
      tailscale_oauth_secret: ${{ secrets.TAILSCALE_OAUTH_SECRET }}
      build_secrets: |
        FETCH_GH_TOKEN=${{ secrets.GITHUB_TOKEN }}
