---
# yamllint disable rule:line-length
name: "test image"

on:
  pull_request:
    paths:
    - 'images/homelab-workspace/**'
    - '.github/workflows/test-image.yaml'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build-workspace-image:
    uses: ppat/github-workflows/.github/workflows/build-docker-image.yaml@v0.1.1
    with:
      image_context_path: images/homelab-workspace
      label_title: "Homelab Workspace"
      label_description: "Homelab workspace image"
      platforms: linux/amd64,linux/arm64
      private_registry_repository: ${{ vars.CONTAINER_REGISTRY_PATH }}/coder-workspace
      private_registry_build_cache: ${{ vars.CONTAINER_REGISTRY_CACHE_PATH }}/coder-workspace
      source_git_ref: ${{ (github.event_name == 'pull_request') && format('refs/heads/{0}', github.head_ref) || github.ref }}
      timeout_minutes: 180
    secrets:
      private_registry_username: ${{ secrets.CONTAINER_REGISTRY_USERNAME }}
      private_registry_token: ${{ secrets.CONTAINER_REGISTRY_PASSWORD }}
      private_registry: ${{ secrets.CONTAINER_REGISTRY }}
      tailscale_oauth_client_id: ${{ secrets.TAILSCALE_OAUTH_CLIENT_ID }}
      tailscale_oauth_secret: ${{ secrets.TAILSCALE_OAUTH_SECRET }}
      build_secrets: |
        FETCH_GH_TOKEN=${{ secrets.GITHUB_TOKEN }}
